name: "flight_price_tracker"
version: "1.0.0"
config-version: 2

profile: "flight_price_tracker"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

# Default configs for all models unless overridden
models:
  flight_price_tracker:
    +database: FLIGHT_DB
    # We'll direct models into schemas by folder:
    stg:
      +schema: STG
      +materialized: view
    core:
      +schema: CORE
      +materialized: table
    mart:
      +schema: MART
      +materialized: table