version: 2

models:
  - name: mart_lowest_price_by_route_date
    description: History of lowest price per route & departure date for each quote_day (analysis-ready)
    columns:
      - name: route_code
        tests: [not_null]
      - name: origin
        tests: [not_null]
      - name: destination
        tests: [not_null]
      - name: departure_date
        tests: [not_null]
      - name: quote_day
        tests: [not_null]
      - name: daily_min_price_aud
        tests: [not_null]
      - name: observed_at
        tests: [not_null]

    tests:
      # Ensure one row per (route_code, departure_date, quote_day)
      - unique:
          column_name: "route_code || '-' || cast(departure_date as string) || '-' || cast(quote_day as string)"